export const FETCH_HADMIN_USER_LIST = "FETCH_HADMIN_USER_LIST";
export const FETCH_HADMIN_APPOINTMENT_LIST = "FETCH_HADMIN_APPOINTMENT_LIST";
export const FETCH_HADMIN_HOSPITAL = "FETCH_HADMIN_HOSPITAL";
