export const FETCH_HADMIN_USER_LIST = "FETCH_HADMIN_USER_LIST";
export const FETCH_HADMIN_APPOINTMENT_LIST = "FETCH_HADMIN_APPOINTMENT_LIST";
export const FETCH_HADMIN_HOSPITAL = "FETCH_HADMIN_HOSPITAL";
export const FETCH_HADMIN_APPOINTMENT_LIST_AFTER_CREATE =
  "FETCH_HADMIN_APPOINTMENT_LIST_AFTER_CREATE";
export const FETCH_HADMIN_APPOINTMENT_DETAIL_AFTER_UPDATE =
  "FETCH_HADMIN_APPOINTMENT_DETAIL_AFTER_UPDATE";
export const FETCH_HADMIN_APPOINTMENT_DETAIL =
  "FETCH_HADMIN_APPOINTMENT_DETAIL";
